### ISSUE TITLE
Neighbor::Error when trying to create a blueprint

### ISSUE THREAD

**Issue by phaedryx** [sublayerapp/blueprints#21]
I am using the VSCode extension to try to create blueprints locally. I have the server configured to use Gemini.

It seems to submit my code to `/Users/tadthorley/repos/blueprints/app/controllers/api/v1/blueprints_controller.rb` accurately, and also create the categories. However, the blueprint itself doesn't save and the endpoint returns a 500 error to the VSCode extension. The error I'm getting is
```
Neighbor::Error: Expected 1536 dimensions, not 768
```

Which originates from the `neighbor` gem.

**Comment by swerner** [comment]
Ugh I'm really sorry about this, we weren't expecting anyone to need to change embedding/model providers after setting up the project. The issue is that the Gemini embeddings use a different format from OpenAI embeddings so the database needs to be set up from the beginning for which embedding model to use. To be able to fully use the gemini embeddings and code generation you need to drop the database and recreate it with the gemini configuration.

**Comment by phaedryx** [comment]
That worked, thank you
